before_script:
  - rm -rf /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - mkdir -p /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - cp -r ./. /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - cd /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - source ~/.ossenv

variables:
  PROJECT: "datakit"

stages:
  - deploy

release-nothing-only-build:
  stage: deploy
  only:
    - /^dev-.*$/
    - /^iss-.*$/
  script:
    # only building
    - make clean
    - make deps
    - make lint
    - make all_test
    - make testing GIT_BRANCH=$CI_COMMIT_BRANCH
    - make check_conf_compatible
  tags:
    - cloudcare-ft

release-testing:
  stage: deploy
  only:
    - testing
    - hotfix
    - /^testing-.*$/
  script:
    # building && publish testing
    - make clean
    - make deps
    - make lint
    - make all_test
    - make testing GIT_BRANCH=$CI_COMMIT_BRANCH
    - make check_conf_compatible
    - make pub_testing
    - make pub_testing_img
  tags:
    - cloudcare-ft

release-production:
  stage: deploy
  only:
    - master
  script:
    - make clean
    - make deps
    - make lint
    - make all_test
    - make production GIT_BRANCH=$CI_COMMIT_BRANCH
    - make check_conf_compatible
    - make pub_production
    - make pub_production_img
  tags:
    - cloudcare-ft
