before_script:
  - rm -rf /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - mkdir -p /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - cp -r ./. /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - cd /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - source ~/.ossenv

variables:
  PROJECT: "datakit"

stages:
  - deploy

release-testing:
  stage: deploy
  only:
    - testing
    - hotfix
    - /^testing-.*$/
  script:
    # building && publish testing
    - make clean
    - make lint
    - make all_test
    - make testing GIT_BRANCH=$CI_COMMIT_BRANCH # do not set VERSION here, use git version
    - make check_testing_conf_compatible
    - make testing_image
  tags:
    - cloudcare-ft

release-stable:
  stage: deploy
  only:
    - master
  script:
    - make clean
    - make lint
    - make all_test
    - make production GIT_BRANCH=$CI_COMMIT_BRANCH VERSION=1.2.14 # update the version on each release
    - make check_production_conf_compatible
    - make pub_conf_samples
    - make production_image GIT_BRANCH=$CI_COMMIT_BRANCH VERSION=1.2.14
  tags:
    - cloudcare-ft

release-unstable:
  stage: deploy
  only:
    - community # 专用分支来发布 community 版本
  script:
    - make clean
    - make lint
    - make all_test
    - make production GIT_BRANCH=$CI_COMMIT_BRANCH VERSION=1.3.1
    - make check_production_conf_compatible
    - make production_image VERSION=1.3.1
  tags:
    - cloudcare-ft

# for testing current issue, should delete after merge into master
current-testing:
  stage: deploy
  only:
    - /^xxx-.*$/
  script:
    - make clean
    - make testing GIT_BRANCH=$CI_COMMIT_BRANCH VERSION=1.999.0
    - make testing_image VERSION=1.999.0
  tags:
    - cloudcare-ft
