[run]
  timeout = "10m"
  skip-files = []
  skip-dirs = [
    #"pkg/provider/kubernetes/crd/generated/",
  ]

[linters-settings]

  [linters-settings.govet]
    check-shadowing = false

  [linters-settings.golint]
    min-confidence = 0.0

  [linters-settings.gocyclo]
    min-complexity = 14.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 4.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.funlen]
    lines = 230 # default 60
    statements = 120 # default 40

  [linters-settings.forbidigo]
    forbid = [
      '^print(ln)?$',
      '^spew\.Print(f|ln)?$',
      '^spew\.Dump$',
    ]

  [linters-settings.depguard]
    list-type = "blacklist"
    include-go-root = false
    packages = ["github.com/pkg/errors"]

  [linters-settings.godox]
    keywords = ["FIXME"]

  [linters-settings.importas]
    corev1 = "k8s.io/api/core/v1"
    networkingv1beta1 = "k8s.io/api/networking/v1beta1"
    extensionsv1beta1 = "k8s.io/api/extensions/v1beta1"
    metav1 = "k8s.io/apimachinery/pkg/apis/meta/v1"
    kubeerror = "k8s.io/apimachinery/pkg/api/errors"

  [linters-settings.gomoddirectives]
    replace-allow-list = [
      "github.com/abbot/go-http-auth",
      "github.com/go-check/check",
      "github.com/gorilla/mux",
      "github.com/mailgun/minheap",
      "github.com/mailgun/multibuf",
    ]

[linters]
  enable-all = true
  disable = [
    "sqlclosecheck", # Not relevant (SQL)
    "rowserrcheck", # Not relevant (SQL)
    "lll", # Not relevant
    "gocyclo", # FIXME must be fixed
    "gocognit", # Too strict
    "nestif", # Too many false-positive.
    "prealloc", # Too many false-positive.
    "makezero", # Not relevant
    "dupl", # Too strict
    "gosec", # Too strict
    "gochecknoinits",
    "gochecknoglobals",
    "wsl", # Too strict
    "nlreturn", # Not relevant
    "gomnd", # Too strict
    "stylecheck", # skip because report issues related to some generated files.
    "testpackage", # Too strict
    "tparallel", # Not relevant
    "paralleltest", # Not relevant
    "exhaustive", # Not relevant
    "exhaustivestruct", # Not relevant
    "goerr113", # Too strict
    "wrapcheck", # Too strict
    "noctx", # Too strict
    "bodyclose", # Too many false-positive and panics.
    "unparam", # Too strict
    "godox", # Too strict
		"nolintlint",
		"golint", # Too strict
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = [
  ]
 [[issues.exclude-rules]]
    path = "(.+)_test.go"
    linters = ["goconst", "funlen", "godot"]
