# Default values for datakit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: pubrepo.jiagouyun.com/datakit/datakit
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{tag}}"

# https://www.yuque.com/dataflux/datakit/datakit-install#f9858758

dataway_url: https://openway.guance.com?token=<your-token>

global_tags: host=__datakit_hostname,host_ip=__datakit_ip

default_enabled_inputs: cpu,disk,diskio,mem,swap,system,hostobject,net,host_processes,container

enabled_election: true

log: stdout

http_listen: 0.0.0.0:9529

git_repos:
  enable: false
  git_url: "-"
  git_key_path: "-"
  git_key_pw: "-"
  git_branch: "master"
  git_interval: "1m"


extraEnvs: []
#  - name: "NODE_OPTIONS"
#    value: "--max-old-space-size=1800"

nameOverride: ""
fullnameOverride: ""


podAnnotations:
  datakit/logs: |
    [{"disable": true}]


tolerations:
  - operator: Exists

service:
  type: ClusterIP
  port: 9529

dkconfig: []
#  - path: "/usr/local/datakit/conf.d/db/mysql.conf"
#    name: mysql.conf
#    value: |
#      # {"version": "1.1.9-rc7.1", "desc": "do NOT edit this line"}
#      [[inputs.mysql]]
#        host = "192.168.0.3"
#        user = "root"
#        pass = "S6QgMvrer2!8xvMD"
#        port = 3306
#        interval = "10s"
#        innodb = true
#        tables = []
#        users = []
#        [inputs.mysql.dbm_metric]
#          enabled = true
#        ## 监控采样配置
#        [inputs.mysql.dbm_sample]
#          enabled = true
#        [inputs.mysql.tags]
#          # some_tag = "some_value"
#          # more_tag = "some_other_value"
#

